<?php

namespace ApiBundle\Repository;
use ApiBundle\Entity\Bookmark;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookmarkRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $page
     * @param int $offset
     * @return ArrayCollection|Bookmark[]
     */
    public function findPerPage(int $page, int $offset): array {
        return $this
            ->createQueryBuilder('b')
            ->setMaxResults($offset)
            ->setFirstResult(($page - 1) * $offset)
            ->orderBy('b.addedDate', 'DESC')
            ->getQuery()
            ->getResult();

    }
}
