<?php

namespace ApiBundle\Repository;

/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookmarkRepository extends \Doctrine\ORM\EntityRepository
{
}
